const QUOTES = [
  "It's you vs you.",
  "Discipline is doing what needs to be done, even if you don't want to do it.",
  "Your only limit is your mind.",
  "Don't stop when you're tired. Stop when you're done.",
  "Hard work beats talent when talent doesn't work hard.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never came from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The only bad workout is the one that didn't happen.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s not about having time. It’s about making time.",
  "The bad news is time flies. The good news is you’re the pilot.",
  "Don't let yesterday take up too much of today.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you can dream it, you can do it.",
  "Aim for the moon. If you miss, you may hit a star.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen, you create them.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do what you can, with what you have, where you are.",
  "Everything has beauty, but not everyone can see.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Happiness depends upon ourselves.",
  "To handle yourself, use your head; to handle others, use your heart.",
  "The only true wisdom is in knowing you know nothing.",
  "Knowing yourself is the beginning of all wisdom.",
  "Education is the most powerful weapon which you can use to change the world.",
  "Obsessed is just a word the lazy use to describe the dedicated.",
  "You didn't come this far to only come this far.",
  "Focus on the goal, not the obstacle.",
  "Be stronger than your excuses.",
  "Sweat is just fat crying.",
  "Train insane or remain the same.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Your body can stand almost anything. It’s your mind that you have to convince.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "A one hour workout is 4% of your day. No excuses.",
  "Someone busier than you is working out right now.",
  "Hustle for that muscle.",
  "Go the extra mile. It's never crowded there.",
  "Believe you can and you're halfway there.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "Quality is not an act, it is a habit.",
  "Action is the foundational key to all success.",
];

export const getDailyQuote = (date) => {
  const d = new Date(date);
  const seed = d.getFullYear() * 1000 + d.getMonth() * 100 + d.getDate();
  return QUOTES[seed % QUOTES.length];
};
